import "./blog.scss";

export type BlogPost = {
  title: string;
  date: string;
  description: string;
  permalink: string;
};

export type BlogFeedResult =
  | { ok: true; pages: BlogPost[] }
  | {
      ok: false;
      // `no_token` is retained for type-shape backward compatibility with
      // any caller still discriminating on it, but the same-origin
      // /api/pages.json feed introduced in D5 no longer produces this
      // reason: a missing static asset surfaces as `http_error` (404).
      reason: "no_token" | "http_error" | "network_error" | "parse_error";
      status?: number;
    };

// D5: the blog now lives on the same origin under /blog. The old
// blog.thetyster.dev subdomain has been collapsed; links point at the
// in-app routes generated by app/blog/[slug]/page.tsx.
const BLOG_HOME = "/blog";

function FallbackLink({ note }: { note: string }) {
  return (
    <p className="blog-fallback">
      {note}{" "}
      <a href={BLOG_HOME}>
        Visit the blog index →
      </a>
    </p>
  );
}

function formatDate(date: string): string {
  if (!date) return "";
  const parsed = new Date(date);
  if (Number.isNaN(parsed.getTime())) return date;
  return parsed.toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function Blog({ blogFeed }: { blogFeed: BlogFeedResult }) {
  if (blogFeed.ok === false) {
    const note =
      blogFeed.reason === "no_token"
        ? "Blog feed unavailable in this environment."
        : "Couldn't load posts right now.";
    return (
      <div className="blog">
        <FallbackLink note={note} />
      </div>
    );
  }

  const posts = blogFeed.pages;
  if (posts.length === 0) {
    return (
      <div className="blog">
        <FallbackLink note="No posts yet." />
      </div>
    );
  }

  return (
    <div className="blog">
      <ul className="blog-list">
        {posts.map((post) => (
          <li key={post.permalink} className="blog-post">
            <a href={post.permalink}>
              <h3>{post.title}</h3>
            </a>
            {post.date ? (
              <time dateTime={post.date} className="blog-date">
                {formatDate(post.date)}
              </time>
            ) : null}
            {post.description ? (
              <p className="blog-description">{post.description}</p>
            ) : null}
          </li>
        ))}
      </ul>
      <p className="blog-more">
        <a href={BLOG_HOME}>
          More on the blog →
        </a>
      </p>
    </div>
  );
}



export default Blog;
